# Generated by Django 5.0.1 on 2024-04-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder',
            field=models.IntegerField(default=5),
        ),
    ]
