# Generated by Django 5.0.1 on 2024-05-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_reorders'),
    ]

    operations = [
        migrations.AddField(
            model_name='reorders',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('canceled', 'Canceled')], default='Sent', max_length=10),
        ),
    ]
