# Generated by Django 5.0.1 on 2024-05-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_reorders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reorders',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('canceled', 'Canceled'), ('updated', 'Stock Updated')], default='sent', max_length=10),
        ),
    ]
