# Generated by Django 5.0.1 on 2024-05-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_reorders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='John', max_length=50),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='Doe', max_length=50),
        ),
    ]
